baseURL = "https://seconomica.com"
languageCode = "es"
title = "Solución Económica"
theme = "timer"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

#[[menu.main]]
#name = "Acerca de"
#url = "about/"
#weight = 2


[[menu.main]]
name = "Ofertas"
url = "gallery/"
weight = 3

[[menu.main]]
name = "Requisitos"
url = "service/"
weight = 4

#[[menu.main]]
#name = "Blog"
#url = "blog/"
#weight = 5

[[menu.main]]
name = "Contacto"
url = "contact/"
weight = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Corporativo de Financiamiento y Soluciones crediticias efectivas."
author = "Soluciones Económicas"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "images/slider.jpg"
heading = "Somos la opción definitiva para adquirir tu auto"
description = "Los mejores planes para que adquieras el auto de tus sueños y cumplas hoy tus metas."
# button
btn = true
btnText = "Solicitar crédito"
btnURL = "contact/"

# flip text
[[params.banner.flipText]]
title = "Créditos tradicionales"
[[params.banner.flipText]]
title = "Créditos para plataformas"
[[params.banner.flipText]]
title = "Créditos seminuevos"

# Homepage About Section
[params.about]
enable = false
title = "ABOUT ME"
content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
image = "images/about/about.jpg"

# Call to Action
[params.cta]
enable = true
title = "55 25231735"
content = "Av. Insurgentes sur #1896, piso 10 y 12. Colonia Florida, Álvaro Obregón, CDMX, CP 01030 "
btnText = "Contactanos"
btnURL = "https://seconomica.com/contact/"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "Soluciones crediticias"
subtitle = "En Solución Económica ofrecemos distintas ofertas créditicias para que puedas adquirir el vehiculo de tus sueños."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
